<?php declare(strict_types=1);

namespace BitWasp\Bitcoin\Script\Interpreter;

const VALIDATION_WEIGHT_OFFSET = 50;
const TAPROOT_LEAF_MASK = 0xfe;
const TAPROOT_LEAF_TAPSCRIPT = 0xc0;
const TAPROOT_CONTROL_BASE_SIZE = 33;
const TAPROOT_CONTROL_BRANCH_SIZE = 32;
const TAPROOT_CONTROL_MAX_DEPTH = 128;
const TAPROOT_CONTROL_MAX_SIZE = TAPROOT_CONTROL_BASE_SIZE + (TAPROOT_CONTROL_BRANCH_SIZE * TAPROOT_CONTROL_MAX_DEPTH);